import type { Influencer, Tag, User } from "./types"

export const mockInfluencers: Influencer[] = [
  {
    id: "1",
    name: "Sarah Chen",
    avatar: "/professional-woman-tech.jpg",
    bio: "Tech entrepreneur and digital marketing expert with 8+ years of experience.",
    category: "Technology",
    niche: ["Digital Marketing", "SaaS", "Startups"],
    platforms: {
      twitter: "@sarahchen",
      linkedin: "sarahchen",
      youtube: "@sarahchen",
    },
    credibilityRating: 87,
    engagementRate: 6.2,
    growthStability: 8.5,
    contentQuality: 8.8,
    authenticity: 8.2,
    followers: 145000,
    verified: true,
    status: "approved",
    trustTags: ["Transparent", "Consistent", "Expert Knowledge", "Audience Engagement"],
    joinedDate: "2023-06-15",
    ratingHistory: [
      { date: "2025-01-01", rating: 82, change: 0 },
      { date: "2024-10-01", rating: 85, change: 3 },
      { date: "2024-07-01", rating: 82, change: 1 },
      { date: "2024-04-01", rating: 81, change: 2 },
    ],
  },
  {
    id: "2",
    name: "Marcus Johnson",
    avatar: "/professional-man-creative.jpg",
    bio: "Creative director specializing in brand storytelling and visual design.",
    category: "Design & Creative",
    niche: ["Branding", "Visual Design", "Content Creation"],
    platforms: {
      instagram: "@marcusjohn",
      tiktok: "@marcusjohn",
      youtube: "@marcusjohn",
    },
    credibilityRating: 76,
    engagementRate: 7.8,
    growthStability: 7.2,
    contentQuality: 7.9,
    authenticity: 7.5,
    followers: 89000,
    verified: true,
    status: "approved",
    trustTags: ["Creative Vision", "Consistent Output", "Community Focused"],
    joinedDate: "2023-08-22",
    ratingHistory: [
      { date: "2025-01-01", rating: 76, change: 1 },
      { date: "2024-10-01", rating: 75, change: 2 },
      { date: "2024-07-01", rating: 73, change: 0 },
      { date: "2024-04-01", rating: 73, change: -1 },
    ],
  },
  {
    id: "3",
    name: "Elena Vasquez",
    avatar: "/professional-woman-business.jpg",
    bio: "Business strategy consultant and thought leader in corporate innovation.",
    category: "Business",
    niche: ["Corporate Strategy", "Innovation", "Leadership"],
    platforms: {
      linkedin: "elenvasquez",
      twitter: "@elenavq",
    },
    credibilityRating: 92,
    engagementRate: 5.1,
    growthStability: 9.2,
    contentQuality: 9.5,
    authenticity: 9.1,
    followers: 234000,
    verified: true,
    status: "approved",
    trustTags: ["Industry Expert", "Thought Leader", "Authentic Voice", "Data Driven"],
    joinedDate: "2022-03-10",
    ratingHistory: [
      { date: "2025-01-01", rating: 92, change: 1 },
      { date: "2024-10-01", rating: 91, change: 2 },
      { date: "2024-07-01", rating: 89, change: 3 },
      { date: "2024-04-01", rating: 86, change: 2 },
    ],
  },
  {
    id: "4",
    name: "David Kim",
    avatar: "/professional-man-tech.jpg",
    bio: "Software engineer and open-source advocate passionate about community.",
    category: "Technology",
    niche: ["Open Source", "Software Development", "Web3"],
    platforms: {
      github: "davidkim",
      twitter: "@davidkim_dev",
      linkedin: "davidkim",
    },
    credibilityRating: 81,
    engagementRate: 4.5,
    growthStability: 8.8,
    contentQuality: 8.6,
    authenticity: 8.9,
    followers: 67000,
    verified: true,
    status: "approved",
    trustTags: ["Technical Depth", "Community Builder", "Transparent", "Consistent"],
    joinedDate: "2023-02-14",
    ratingHistory: [
      { date: "2025-01-01", rating: 81, change: 2 },
      { date: "2024-10-01", rating: 79, change: 1 },
      { date: "2024-07-01", rating: 78, change: 2 },
      { date: "2024-04-01", rating: 76, change: 0 },
    ],
  },
  {
    id: "5",
    name: "Sophia Rodriguez",
    avatar: "/professional-woman-marketing.jpg",
    bio: "Marketing strategist and growth hacker for B2B SaaS companies.",
    category: "Marketing",
    niche: ["Growth Marketing", "SaaS", "B2B Strategy"],
    platforms: {
      linkedin: "sophiarodriguez",
      twitter: "@sophiam",
      substack: "sophiam",
    },
    credibilityRating: 79,
    engagementRate: 5.8,
    growthStability: 7.9,
    contentQuality: 8.1,
    authenticity: 7.8,
    followers: 112000,
    verified: false,
    status: "pending",
    trustTags: ["Growth Expert", "Data Driven", "Emerging Voice"],
    joinedDate: "2024-05-20",
    ratingHistory: [
      { date: "2025-01-01", rating: 79, change: 0 },
      { date: "2024-11-01", rating: 79, change: 1 },
    ],
  },
]

export const mockTags: Tag[] = [
  {
    id: "1",
    label: "Transparent",
    category: "trust",
    description: "Clear communication with audience about partnerships and data",
  },
  {
    id: "2",
    label: "Consistent",
    category: "content",
    description: "Regular publishing schedule and content quality",
  },
  {
    id: "3",
    label: "Expert Knowledge",
    category: "content",
    description: "Demonstrates deep expertise in their niche",
  },
  {
    id: "4",
    label: "Audience Engagement",
    category: "engagement",
    description: "High interaction rates and community responsiveness",
  },
  {
    id: "5",
    label: "Thought Leader",
    category: "trust",
    description: "Original insights and industry influence",
  },
  {
    id: "6",
    label: "Growth Stability",
    category: "growth",
    description: "Steady and sustainable audience growth",
  },
  {
    id: "7",
    label: "Authentic Voice",
    category: "trust",
    description: "Genuine personality and real opinions",
  },
  {
    id: "8",
    label: "Data Driven",
    category: "content",
    description: "Backs claims with research and metrics",
  },
]

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alex Johnson",
    email: "alex@example.com",
    role: "brand",
    avatar: "/brand-manager.jpg",
  },
  {
    id: "user-2",
    name: "Jamie Smith",
    email: "jamie@example.com",
    role: "influencer",
    avatar: "/influencer-profile.jpg",
  },
  {
    id: "user-3",
    name: "Admin",
    email: "admin@example.com",
    role: "admin",
    avatar: "/admin-user.jpg",
  },
]

export const mockCurrentUser: User = {
  id: "current-user",
  name: "Current User",
  email: "user@example.com",
  role: "brand",
  avatar: "/abstract-user-representation.png",
}
